"""
MCP-4: Sanctions & Risk Tools (UPDATED - USES REAL DATA)
---------------------------------------------------------
Tools for checking sanctions lists and risk databases.

Functions:
- check_sanctions_list(company_name, owner_name): Check against REAL sanctions lists
- check_watchlist(registration_number): Check risk watchlists

Data Sources: 
✅ REAL DATA from:
   - EU Consolidated Financial Sanctions (CSV)
   - OFAC SDN List (CSV)
   - UN Security Council Sanctions (XML)

Note: Run sanctions_data_loader.py first to generate the combined JSON file.
"""

import logging
from typing import Dict, List, Any, Optional
from pathlib import Path
import json

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Global cache for sanctions data (loaded once at startup)
_SANCTIONS_CACHE = None


def _load_sanctions_data() -> Dict[str, Any]:
    """
    Load sanctions data from JSON file (generated by sanctions_data_loader.py).
    
    Returns:
        Dict with sanctions data
    """
    global _SANCTIONS_CACHE
    
    if _SANCTIONS_CACHE is not None:
        return _SANCTIONS_CACHE
    
    try:
        sanctions_file = Path("data/mock_external_data/sanctions/sanctions_combined.json")
        
        if not sanctions_file.exists():
            logger.warning(f"Sanctions data file not found: {sanctions_file}")
            logger.warning("Run: python mcp_tools/sanctions_data_loader.py to generate it")
            return _get_empty_sanctions_data()
        
        with open(sanctions_file, 'r', encoding='utf-8') as f:
            _SANCTIONS_CACHE = json.load(f)
        
        logger.info(f"Loaded sanctions data: {_SANCTIONS_CACHE['total_entities']} entities, {_SANCTIONS_CACHE['total_individuals']} individuals")
        
        return _SANCTIONS_CACHE
    
    except Exception as e:
        logger.error(f"Failed to load sanctions data: {e}")
        return _get_empty_sanctions_data()


def _get_empty_sanctions_data() -> Dict[str, Any]:
    """Return empty sanctions data structure."""
    return {
        'entities': [],
        'individuals': [],
        'total_entities': 0,
        'total_individuals': 0,
        'sources': {}
    }


def check_sanctions_list(
    company_name: str, 
    owner_names: Optional[List[str]] = None
) -> Dict[str, Any]:
    """
    Check if a company or its owners appear on REAL sanctions lists.
    
    This function checks against:
    - EU Consolidated Sanctions List (REAL DATA ✅)
    - OFAC SDN List (REAL DATA ✅)
    - UN Security Council Sanctions List (REAL DATA ✅)
    
    Args:
        company_name (str): Company name to check
        owner_names (List[str], optional): List of owner/director names to check
        
    Returns:
        Dict containing:
        - 'success' (bool): Whether check was performed
        - 'company_matches' (List[Dict]): Any matches for company name
        - 'owner_matches' (List[Dict]): Any matches for owners
        - 'total_matches' (int): Total number of matches found
        - 'lists_checked' (List[str]): Which sanctions lists were checked
        - 'risk_level' (str): 'clear', 'warning', or 'blocked'
        
    Example:
        >>> result = check_sanctions_list("ABC Company Ltd", ["John Smith", "Jane Doe"])
        >>> print(result['risk_level'])
        'clear'
        >>> print(result['total_matches'])
        0
    """
    try:
        logger.info(f"Checking REAL sanctions lists for: {company_name}")
        
        # Load sanctions data
        sanctions_data = _load_sanctions_data()
        
        if sanctions_data['total_entities'] == 0 and sanctions_data['total_individuals'] == 0:
            logger.warning("No sanctions data loaded. Results may be inaccurate.")
        
        if owner_names:
            logger.info(f"Also checking {len(owner_names)} owner names")
        
        # Check company name
        company_matches = []
        company_name_lower = company_name.lower().strip()
        
        # Exact match
        if company_name_lower in sanctions_data['entities']:
            company_matches.append({
                'matched_name': company_name_lower,
                'list': 'Combined Sanctions Database',
                'match_type': 'exact',
                'severity': 'high'
            })
        
        # Partial match (contains)
        for entity in sanctions_data['entities']:
            if company_name_lower in entity or entity in company_name_lower:
                if company_name_lower != entity:  # Don't duplicate exact matches
                    company_matches.append({
                        'matched_name': entity,
                        'list': 'Combined Sanctions Database',
                        'match_type': 'partial',
                        'severity': 'medium'
                    })
                    if len(company_matches) >= 10:  # Limit to top 10 partial matches
                        break
        
        # Check owner names
        owner_matches = []
        if owner_names:
            for owner in owner_names:
                owner_lower = owner.lower().strip()
                
                # Exact match
                if owner_lower in sanctions_data['individuals']:
                    owner_matches.append({
                        'matched_name': owner_lower,
                        'searched_name': owner,
                        'list': 'Combined Sanctions Database',
                        'match_type': 'exact',
                        'severity': 'high'
                    })
                
                # Partial match
                for individual in sanctions_data['individuals']:
                    if owner_lower in individual or individual in owner_lower:
                        if owner_lower != individual:
                            owner_matches.append({
                                'matched_name': individual,
                                'searched_name': owner,
                                'list': 'Combined Sanctions Database',
                                'match_type': 'partial',
                                'severity': 'medium'
                            })
                            if len(owner_matches) >= 10:
                                break
        
        # Determine risk level
        exact_matches = [m for m in company_matches + owner_matches if m.get('match_type') == 'exact']
        partial_matches = [m for m in company_matches + owner_matches if m.get('match_type') == 'partial']
        
        if exact_matches:
            risk_level = 'blocked'
            message = f"🚨 CRITICAL: Found {len(exact_matches)} EXACT match(es) in sanctions lists"
        elif partial_matches:
            risk_level = 'warning'
            message = f"⚠️ WARNING: Found {len(partial_matches)} partial match(es) in sanctions lists"
        else:
            risk_level = 'clear'
            message = "✅ No matches found in sanctions lists"
        
        result = {
            'success': True,
            'company_name': company_name,
            'company_matches': company_matches,
            'owner_matches': owner_matches,
            'total_matches': len(company_matches) + len(owner_matches),
            'exact_matches': len(exact_matches),
            'partial_matches_count': len(partial_matches),
            'lists_checked': list(sanctions_data['sources'].keys()),
            'risk_level': risk_level,
            'message': message,
            'data_source': f"Real sanctions data: {sanctions_data['total_entities']} entities, {sanctions_data['total_individuals']} individuals"
        }
        
        logger.info(f"Sanctions check complete: {message}")
        
        return result
    
    except Exception as e:
        logger.error(f"Failed to check sanctions lists: {e}")
        return {
            'success': False,
            'error': str(e),
            'company_name': company_name,
            'total_matches': 0,
            'risk_level': 'unknown'
        }


def check_watchlist(registration_number: str, country: str = "UK") -> Dict[str, Any]:
    """
    Check if a company appears on risk watchlists.
    
    Watchlists include:
    - Financial crime watchlists
    - Regulatory enforcement actions
    - Industry-specific risk databases
    - Adverse media databases
    
    Args:
        registration_number (str): Company registration number
        country (str): Country code (default: "UK")
        
    Returns:
        Dict containing:
        - 'success' (bool): Whether check was performed
        - 'watchlist_matches' (List[Dict]): Any matches found
        - 'match_count' (int): Number of matches
        - 'risk_level' (str): 'clear', 'low', 'medium', 'high'
        - 'sources_checked' (List[str]): Which watchlists were checked
        
    Example:
        >>> result = check_watchlist("12345678", "UK")
        >>> print(result['risk_level'])
        'clear'
    """
    try:
        logger.info(f"Checking watchlists for registration: {registration_number} ({country})")
        
        # Sources that would be checked in production
        sources_checked = [
            'Financial Conduct Authority (FCA) Warning List',
            'HMRC Tax Defaulters',
            'Companies House Enforcement Actions',
            'Credit Risk Databases',
            'Adverse Media Database'
        ]
        
        # Mock implementation - in production, would query actual databases
        watchlist_matches = []
        
        # Simulate a clean record (no matches)
        # In production, you would query each database
        
        result = {
            'success': True,
            'registration_number': registration_number,
            'country': country,
            'watchlist_matches': watchlist_matches,
            'match_count': len(watchlist_matches),
            'risk_level': 'clear',
            'sources_checked': sources_checked,
            'message': '✅ No adverse records found in watchlists',
            'note': 'Mock check - In production, would query actual watchlist databases'
        }
        
        logger.info("Watchlist check complete: No matches found")
        
        return result
    
    except Exception as e:
        logger.error(f"Failed to check watchlists: {e}")
        return {
            'success': False,
            'error': str(e),
            'registration_number': registration_number,
            'match_count': 0,
            'risk_level': 'unknown'
        }


# Test function
if __name__ == "__main__":
    print("=" * 80)
    print("TESTING MCP-4: SANCTIONS & RISK TOOLS (WITH REAL DATA)")
    print("=" * 80)
    
    # Test 1: Check clean company
    print("\n[TEST 1] Checking clean company...")
    result1 = check_sanctions_list("TechTextiles Ltd", ["John Smith", "Sarah Johnson"])
    
    print(f"   Company: {result1['company_name']}")
    print(f"   Risk Level: {result1['risk_level']}")
    print(f"   Total Matches: {result1['total_matches']}")
    print(f"   Exact Matches: {result1.get('exact_matches', 0)}")
    print(f"   Partial Matches: {result1.get('partial_matches_count', 0)}")
    print(f"   Lists Checked: {', '.join(result1['lists_checked']) if result1['lists_checked'] else 'None'}")
    print(f"   {result1['message']}")
    print(f"   Data Source: {result1.get('data_source', 'Unknown')}")
    
    # Test 2: Check watchlist
    print("\n[TEST 2] Checking watchlists...")
    result2 = check_watchlist("12345678", "UK")
    
    print(f"   Registration: {result2['registration_number']}")
    print(f"   Country: {result2['country']}")
    print(f"   Risk Level: {result2['risk_level']}")
    print(f"   Matches: {result2['match_count']}")
    print(f"   {result2['message']}")
    
    print("\n" + "=" * 80)
    print("SANCTIONS TOOLS TEST COMPLETE")
    print("=" * 80)
    print("\n💡 TIP: If sanctions data shows 0 entries, run:")
    print("   python mcp_tools/sanctions_data_loader.py")